### ISSUE TITLE
KeyError: 'headless'

### ISSUE THREAD

**Issue by EconomicDead** [Its3rr0rsWRLD/WebshareGenerator#1]
[?] How many threads would you like to run? > 1

! This is only if you are getting rate limited very fast !

Traceback (most recent call last):
  File "C:\Users\Eco\Desktop\WebshareGenerator-main\run.py", line 102, in <module>
    run()
  File "C:\Users\Eco\Desktop\WebshareGenerator-main\run.py", line 40, in run
    if data['headless']:
       ~~~~^^^^^^^^^^^^
KeyError: 'headless'

C:\Users\Eco\Desktop\WebshareGenerator-main>

**Comment by EconomicDead** [comment]
could you please help me fix

**Comment by EconomicDead** [comment]
didnt mean to close mb

**Comment by EconomicDead** [comment]
issue resolved add "headless": false to config

**Comment by Its3rr0rsWRLD** [comment]
Yes, sorry, I forgot to update the config
