### ISSUE TITLE
How can I solve the problem

### ISSUE THREAD

**Issue by ahmedmedo2023** [Its3rr0rsWRLD/WebshareGenerator#2]
![Screenshot 2024-05-05 004835](https://github.com/Its3rr0rsWRLD/WebshareGenerator/assets/129754056/a54455d2-bfd7-4eb6-a224-d91de2d69064)

How can I solve the problem؟

**Comment by Its3rr0rsWRLD** [comment]
Sorry for the late response, but you must have either put the wrong capsolver key in or you are using an unsupported version of python
